

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BeyondVacation.Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class BeyondVacationEntities : DbContext
{
    public BeyondVacationEntities()
        : base("name=BeyondVacationEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<COUNTRY_MST_T> COUNTRY_MST_T { get; set; }

    public virtual DbSet<LOOKUP_DET_T> LOOKUP_DET_T { get; set; }

    public virtual DbSet<LOOKUP_MST_T> LOOKUP_MST_T { get; set; }

}

}

