
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BeyondVacation.Model
{

using System;
    using System.Collections.Generic;
    
public partial class LOOKUP_DET_T
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string LookUpValueCode { get; set; }

    public Nullable<int> LookUpValueOrder { get; set; }

    public Nullable<int> LookUpValueGroupId { get; set; }

    public Nullable<int> LookUpMasterId { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<bool> Active { get; set; }

}

}
